services:
  - type: web
    name: road-sign-detection
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: MAX_UPLOAD_SIZE
        value: 209715200   # 200 MB in bytes
      - key: DATASET_PATH
        value: dataset/Train
    healthCheckPath: /status
